stages:
  - tests

services:
  - docker:19.03.5-dind

image:
  name: docker/compose:1.25.5

variables:
  DOCKER_CERT_PATH: /certs/client
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_TLS_VERIFY: 1

sanity-check:
  stage: .pre
  script:
    - docker info
    - docker version
    - docker-compose version

tests:
  stage: tests
  script:
    - docker-compose -f tests/docker-compose.yml up -d
    - docker-compose -f tests/docker-compose.yml exec -T runner sh -c "composer install"
    - docker-compose -f tests/docker-compose.yml exec -T runner sh -c "vendor/bin/phpunit --testdox"
