filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }
build:
    environment:
        docker: true
        php:
            version: '5.6'
            pecl_extensions:
                - redis-4.3.0
    tests:
        override:
            - 'composer env-up'
            - 'composer test'
