filter:
    excluded_paths:
        - 'tests/'
    dependency_paths:
        - 'vendor/'
checks:
    php: true
coding_style:
    php: {  }
build:
    nodes:
        analysis:
            dependencies:
                override:
                    - composer install --ignore-platform-reqs
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
